import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import Ribbons from "@/compoents/curser-animation/ribbion-curser";
import Footer from "@/compoents/nav/footer";
import { Header } from "@/compoents/nav/header";

const inter = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ margin: 0, padding: 0 }}
      >
        <div style={{ position: "relative", minHeight: "100vh", overflow: "hidden" }}>
          <div style={{ position: "absolute", top: 0, left: 0, width: "100%", height: "100%", zIndex: 10 }}>
            <Ribbons
              baseThickness={40}
              colors={["#3bba9c"]}
              speedMultiplier={0.52}
              maxAge={540}
              enableFade={true}
              enableShaderEffect={false}
            />
          </div>
          <Header />
          <div style={{ position: "relative", zIndex: 1 }}>
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}